Update release hook and fix formatting in release target
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -6,39 +6,45 @@ pkgconfigdir        = $(libdir)/pkgconfig
 pkgconfig_DATA      = libite.pc
 SUBDIRS             = src tests
 
-## Generate .deb package
-package:
-	@dpkg-buildpackage -uc -us -B
-
 ## Generate MD5 checksum file
 MD5 = md5sum
 md5-dist:
-	@for file in $(DIST_ARCHIVES); do							\
-		$(MD5) $$file > $$file.md5;							\
+	@for file in $(DIST_ARCHIVES); do	\
+		$(MD5) $$file > ../$$file.md5;	\
 	done
 
 ## Check if tagged in git
 release-hook:
-	if [ ! `git tag | grep $(PACKAGE_VERSION)` ]; then					\
-		echo;										\
-		printf "\033[1m\033[41mCannot find release tag $(PACKAGE_VERSION)\033[0m\n";	\
-		printf "\033[1m\033[5mDo release anyway?\033[0m "; read yorn;			\
-		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then					\
-			printf "OK, aborting release.\n";					\
-			exit 1;									\
-		fi;										\
-		echo;										\
-	else											\
-		echo;										\
-		printf "\033[1m\033[42mFound GIT release tag $(PACKAGE_VERSION)\033[0m\n";	\
-		printf "\033[1m\033[44m>>Remember to push tags!\033[0m\n";			\
-		echo;										\
+	@if [ ! `git tag | grep $(PACKAGE_VERSION)` ]; then				\
+		echo;									\
+		printf "\e[1m\e[41mCannot find release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[5mDo release anyway?\e[0m "; read yorn;			\
+		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then				\
+			printf "OK, aborting release.\n";				\
+			exit 1;								\
+		fi;									\
+		echo;									\
+	else										\
+		echo;									\
+		printf "\e[1m\e[42mFound GIT release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[44m>>Remember to push tags!\e[0m\n";			\
+		echo;									\
 	fi
 
+# lintian --profile debian -i -I --show-overrides ../$PKG.changes
+package build-deb:
+	@dpkg-buildpackage -uc -us -B
+
 ## Target to run when building a release
-release: distcheck release-hook md5-dist
-	@for file in $(DIST_ARCHIVES); do							\
-		printf "$$file    \tDistribution tarball\n";					\
-		printf "$$file.md5\t"; cat $$file.md5 | cut -f1 -d' ';				\
-		mv $$file* ../;									\
+release: release-hook distcheck package md5-dist
+	@mv $(DIST_ARCHIVES) ../
+	@echo
+	@echo "Resulting release files:"
+	@echo "================================================================="
+	@for file in $(DIST_ARCHIVES); do					\
+		printf "%-32s Distribution tarball\n" $$file;			\
+		printf "%-32s " $$file.md5; cat ../$$file.md5 | cut -f1 -d' ';	\
+	done
+	@for file in `cd ..; ls $(PACKAGE)*_$(VERSION)*`; do			\
+		printf "%-32s Debian/Ubuntu package\n" $$file;			\
 	done
